server:
  port: ${port:8081}

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.29:8847,192.168.1.29:8848,192.168.1.29:8849
    sentinel:
    # 该配置能够使dashboard主动发现该应用
      eager: true
      transport:
      # sentinel注册地址：指定服务端Dashboard的暴露端口
      dashboard: 127.0.0.1:8888
      # 服务接收sentinel的配置端口：接收服务端配置的当前服务端口
      port: 8719
  application:
    name: msc-payment

logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    com.lifei: debug