server:
  port: 8080

spring:
  application:
    name: msc-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8847,127.0.0.1:8848,127.0.0.1:8849

logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    com.lifei: debug